aw - prop
Defra-Data-Science-Centre-of-Excellence/elmo-geo pull request #153
Opened 2024-05-29 15:07 UTC by aw-west-defra

2024-05-31 13:36 UTC, obi-defra requested changes
Looking really good. Have requested a few changes.

I think the main outstanding thing is an analysis of how these proportions compare to ones we've calculated previously, which should be part of this PR to ensure the method works as expected.

2024-05-31 13:36 UTC, obi-defra commented on data/catalogue.json
For this PR I think the only changes to catalogue should be those related to calculating proportions.

This currently has some sjoin related changes showing. Are these changes also present in the sjoin PR (#152)? If not they should be included there.

2024-05-31 13:36 UTC, obi-defra commented on notebooks/ingestion/04_prop.py
> +# Databricks notebook source
Markdown at the start of the notebook need neatening up.

Remove OSM Tags link and To DO list (since these should be done as part of this PR).

2024-05-31 13:36 UTC, obi-defra commented on notebooks/ingestion/04_prop.py
> +
Is st_union needed here? I'm not clear how it is doing anything additional to the ST_Union_Aggr operation used when calcualting the overlap.

2024-05-31 13:36 UTC, obi-defra commented on notebooks/ingestion/04_prop.py
> +def head_and_tail(sdf: SparkDataFrame, skip: int, n: int) -> SparkDataFrame:
I found 'skip' an unclear name. What about 'prop_col_index'?

2024-06-03 18:47 UTC, aw-west-defra commented
I think I just need a better readme and doc functions.

2024-06-05 16:45 UTC, aw-west-defra commented
Showing the head and tail is automatically done when using a PandasDataFrame.

2024-06-05 16:45 UTC, merged