aw - wfm info
Defra-Data-Science-Centre-of-Excellence/elmo-geo pull request #159
Opened 2024-06-05 09:13 UTC by aw-west-defra

I have previously had a dataset "business_info" which calculated arable/grassland which are commonly asked for in reactive analysis.
_(There was also a few other metrics, I've forgotten them, but they can be added later)_

I wanted to formally save it, and I feel this can be merged with centroids from issue #114, and branch [114-parcel-centroids-for-elmo](https://github.com/Defra-Data-Science-Centre-of-Excellence/elmo-geo/tree/114-parcel-centroids-for-elmo)

2024-06-14 17:01 UTC, obi-defra requested changes
Splitting or parcel geometries results in multiple centroid coordinates per id_parcel. Requires a groupby operation in there somewhere.

2024-06-14 17:01 UTC, obi-defra commented on notebooks/ingestion/wfm_info.py
> +sdf = (
sdf has duplicate id_parcel entreis due to parcel geometries being split over sindex tiles.

I don't think the silver dataset should contain these duplicates, as the only columns that differ are the x and y coords. This also means there is a separate centroid for each part of the parcel.

So needs a groupby + ST_Union_Aggr before the centroid calculation.

2024-06-19 09:57 UTC, aw-west-defra commented on notebooks/ingestion/wfm_info.py
> +sdf = (
I believe I've fixed this.
I also added asserts to check it's true.

2024-06-19 16:07 UTC, obi-defra approved these changes
Changes look good.

Check by loading field and farm info data frames, checking for duplicates and checking coordinates not null.

2024-06-20 10:54 UTC, merged