Demo for new ETL/catalog
Defra-Data-Science-Centre-of-Excellence/elmo-geo pull request #167
Opened 2024-07-02 16:44 UTC by burrowsej

2024-07-03 16:32 UTC, aw-west-defra requested changes

2024-07-03 16:36 UTC, burrowsej commented on notebooks/ingestion/demo_new_etl.py
> +)
It would only take time if building the dataset. Takes 2s for me - can you check again?

2024-07-03 16:37 UTC, burrowsej commented on notebooks/ingestion/demo_new_etl.py
> +write_catalog_json()
Intentional as I wanted to avoid a clash with your catalogue - will change in future PR

2024-07-03 16:41 UTC, burrowsej commented on elmo_geo/etl.py
> +
done

2024-07-03 16:41 UTC, burrowsej commented on elmo_geo/datasets/__init__.py
> +        f.write(json.dumps([dataset.dict for dataset in catalog], indent=4))
done

2024-07-03 16:42 UTC, burrowsej commented on elmo_geo/etl.py
future PR please - I have much higher priorities

2024-07-03 16:47 UTC, burrowsej commented on elmo_geo/io/file.py
> +        We are using the experimental geoparquet 1.1 here which saves as geoarrow instead of WKB and
No it doesn't for now - have updated the docstring

2024-07-03 16:54 UTC, burrowsej commented on elmo_geo/datasets/__init__.py
Ok moved to new sub-module called catalog

2024-07-03 17:00 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
1 I don't see this as much work - happy to discuss alternatives but also need to get this merged so let me know when you are free - I'm out most of tomorrow and Friday afternoon

2 is what I have done I think - there is a source_path and a path to the bronze parquet which is untransformed other than CRS

3 no time to look into that - little benefit at present as I don't plan on adding many new datasets

2024-07-03 17:01 UTC, burrowsej commented on elmo_geo/io/file.py
For a future PR please. Not sure what the multi-indexed method is?

2024-07-03 18:21 UTC, aw-west-defra requested changes
For me todo, review hash, rerun demo.
For Ed todo, read "hidden comments" for example df>pdf.

2024-07-03 18:21 UTC, aw-west-defra commented on notebooks/ingestion/demo_new_etl.py
> +write_catalog_json()
I'm fine with that.  It's in the git history if I need it.
Data in bronze is manual, anything in silver can be deleted.

2024-07-03 18:21 UTC, aw-west-defra commented on elmo_geo/datasets/fc_agroforestry.py
```py
source_uri="https://services2.arcgis.com/mHXjwgl3OARRqqD4/ArcGIS/rest/services/SFI_Silvo_Arable/FeatureServer/0"

def fetch_esri(uri: str) -> subprocess.CompletedProcess:
    return subprocess.run(["esri2geojson", uri, self.path], shell=True)
```
I'd also rename SFI Agroforestry to SFI Silvo Arable, to match their database name.

2024-07-04 05:55 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
The dataset is now called SFI Agroforestry as on the Open Data page and is applicable to silvopastoral and silvoarable. It was originally called silvoarable but that would now be confusing so I'm going to leave as is

2024-07-04 05:56 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
> ```python
> source_uri="https://services2.arcgis.com/mHXjwgl3OARRqqD4/ArcGIS/rest/services/SFI_Silvo_Arable/FeatureServer/0"
> 
> def fetch_esri(uri: str) -> subprocess.CompletedProcess:
>     return subprocess.run(["esri2geojson", uri, self.path], shell=True)
> ```
> 
> I'd also rename SFI Agroforestry to SFI Silvo Arable, to match their database name.

Thanks but I still don't want to do this in this PR - would need testing which I'm happy to do in a week or two

2024-07-04 05:58 UTC, burrowsej commented on elmo_geo/etl.py
> +        pat = re.compile(PAT_FMT.format(name=self.name, hsh=self.metahash))
Ok, I will call it _hash I think as it should be "hidden"

2024-07-04 05:59 UTC, burrowsej commented on notebooks/ingestion/demo_new_etl.py
> +write_catalog_json()
Ok but I think we need to talk it through - I don't want to break all the existing ETL if it may take several days to build it again in the new format

2024-07-04 08:33 UTC, burrowsej commented on elmo_geo/etl.py
> +HASH_FMT: str = r"%y%m%d%H%M%S"
done

2024-07-04 08:59 UTC, burrowsej commented on elmo_geo/etl.py
> +        return gdf
yep, pandera docs is the place

2024-07-04 08:59 UTC, burrowsej commented on elmo_geo/etl.py
> +
As discussed, column info is added to the pydantic model as required

2024-07-04 09:18 UTC, burrowsej commented on elmo_geo/etl.py
> +        return time.strftime(HASH_FMT, time.gmtime(os.path.getmtime(self.source_path)))
because source_path is for the source and path is for the parquet data we save.

2024-07-04 09:19 UTC, burrowsej commented on elmo_geo/etl.py
> +    def refresh(self) -> None:
Ok happy to explore this with you in another PR - I've not come across a muti-layer file yet so best if we add in a new PR if ok?

2024-07-04 09:20 UTC, burrowsej commented on notebooks/ingestion/demo_new_etl.py
> +write_catalog_json()
Have removed the old catalogue and renamed all catalog to catalogue

2024-07-04 09:22 UTC, burrowsej commented on elmo_geo/etl.py
> +        return to_sdf(self.gdf(**kwargs))
done

2024-07-04 09:23 UTC, burrowsej commented on elmo_geo/etl.py
> +    def df(self, **kwargs) -> pd.DataFrame:
yes to pdf, we are using `as SparkDataFrame` and the others are `pd.` and `gpd.` which is most common and I'm keen to keep as it is familiar to most devs

2024-07-05 10:59 UTC, aw-west-defra commented on elmo_geo/datasets/fc_agroforestry.py
> +    return ds.gdf(columns=["geometry", "sensitivit"]).rename(columns={"sensitivit": "sensitivity"}).assign(fid=lambda df: range(len(df)))
_func is a terrible name, "sensitivit" might need renaming if we don't download a shapefile.
We will consider an ESRI module.

2024-07-05 11:02 UTC, aw-west-defra commented on elmo_geo/etl.py
> +    def refresh(self) -> None:
TODO: me use ogr2ogr in a separate PR.

2024-07-05 11:13 UTC, aw-west-defra commented on elmo_geo/datasets/__init__.py
- [x] create a catalogue of all datasets `catalogue`
- [x] record the catalogue `write_catalogue_json`
- [x] delete catalogue files `destroy_datasets`
- [ ] create catalogue files

2024-07-05 11:18 UTC, aw-west-defra commented on elmo_geo/etl.py
> +            source_path=self.source_path,
This needs the date last modified.
It's in the path but it could also be in the dictionary for someone for doing data quality analysis.

Worth later considering what other metadata we'd use to analyse the data quality dimensions:
Accuracy, Completeness, Uniqueness, Consistency, Timeliness, Validity

2024-07-05 11:29 UTC, burrowsej commented on elmo_geo/etl.py
> +            source_path=self.source_path,
added date to the json/dict

2024-07-05 11:39 UTC, aw-west-defra commented
- an ESRI module
- ogr2gpq for SourceDataset
- create a JSON suitable for data quality analysis
- create a convert.to_pq method, detect sdf/gdf and saves
- use _func to create lookups and overlaps.

2024-07-05 11:41 UTC, aw-west-defra approved these changes

2024-07-05 11:41 UTC, merged