Add parcels, agroforestry
Defra-Data-Science-Centre-of-Excellence/elmo-geo pull request #172
Opened 2024-07-12 15:40 UTC by burrowsej

Adds:

- `reference_parcels` dataset from RPA - "ADAS"(2021) version
- `sfi_agroforestry_parcels` dataset from intersecting parcels with agroforestry sensitivity

2024-07-15 14:39 UTC, obi-defra requested changes
Couple of changes suggested and one typo corrected.

New etl is very nice for allowing a lot of flexibility and clarity over how data sets and defined and managed. One area to follow up with is making use of some of the functions developed in the ingestion notebooks available for use in the new etl processes.

2024-07-15 14:39 UTC, obi-defra commented on elmo_geo/datasets/fc_agroforestry.py
> +from elmo_geo.st.join import sjoin
The sjoin function in the notebook ingestion/03_sjoin.py should be used as it does not rely on monotonically_increasing_id().

The elmo_geo_st.sjoin function should be overwritten with the sjoin function from the 03_sjoin notebook, and then imported here.

2024-07-15 14:39 UTC, obi-defra commented on elmo_geo/datasets/fc_agroforestry.py
> +    """Only keep the geometry and the sensitivity col, fixing typo in colname."""
Update docstring

2024-07-15 14:39 UTC, obi-defra commented on elmo_geo/datasets/fc_agroforestry.py
> +        sjoin(df_parcels, df_feature)
It's possible that the parcels dataset will have been 'chipped' as part of spatial indexing. This can split parcel geometries across multiple rows.

To control for this, add in a group by id_parcel and sensitivity and union the geometries:

```
        .groupby("id_parcel", *classes)
        .agg(
            F.expr(f"ST_Union_Aggr(geometry_left) AS geometry_left"),
            F.expr(f"ST_Union_Aggr(geometry_right) AS geometry_right"),
        )
```

2024-07-15 14:45 UTC, obi-defra commented on elmo_geo/datasets/fc_agroforestry.py
> +        .where("proportion > 0")
I think adding the groupby suggested above would make this groupby and sum operation redundant.

2024-07-15 15:06 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
> +        .where("proportion > 0")
I don't think it would make it redundant. We are subdivide-exploding the agroforestry polygons and they need grouping up again. A parcel may intersect with two separate polygons of the same class and those intersection area proportions need combining.

2024-07-15 15:39 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
> +        sjoin(df_parcels, df_feature)
Thanks, have made that change

2024-07-15 15:40 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
> +        .where("proportion > 0")
Yep, removed

2024-07-15 15:40 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
> +    """Only keep the geometry and the sensitivity col, fixing typo in colname."""
Done

2024-07-15 15:40 UTC, burrowsej commented on elmo_geo/datasets/fc_agroforestry.py
> +from elmo_geo.st.join import sjoin
Have replaced sjoin with the one from the notebook

2024-07-17 10:14 UTC, obi-defra approved these changes
Changes look good. I made an additional commit of minor changes to the demo new etl notebook so that it works with new fc_agroforestry dataset names.

Inspected the sfi_agroforestry_parcels dataset, checked for duplicates and proportions between 0-1. Looks good.

2024-07-17 10:20 UTC, merged